using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace EquipmentStatusAPI.Entities;

public class EquipmentStatus
{
    [Key]
    [JsonIgnore] // prevent autogenerated Id from being included in JSON request and response
    public Guid Id { get; set; } = Guid.NewGuid();
    public string EquipmentId { get; set; }
    public StatusEnum Status { get; set; }
    
}
